### ISSUE TITLE
meta data vullen

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#20]

**Comment by eoudejans** [comment]
LN metakaartlagen nog (aan) te vullen:
- [ ] H01: totaal energieverbruik
- [ ] H02: energieverbruik ruimteverwarming
- [ ] H03: energieverbruik warm tapwater
- [ ] H04: energieverbruik ventilatie
- [ ] H05: energieverbruik koude
- [ ] H06: energieverbruik apparaten en licht
- [ ] H07: warmteverbruik
- [ ] H08: energielevering
- [ ] H09: energielevering aardgas
- [ ] H10: energielevering duurzaam gas
- [ ] H11: energielevering elektriciteit
- [ ] H12: energielevering MT-warmtebron
- [ ] H13: energielevering LT-warmtebron
- [ ] H14: energielevering overig
- [ ] H15: CO2-uitstoot
- [ ] H16: nationale meerkosten
- [ ] H17: nationale kosten per ton CO2 reductie
- [ ] H18: nationale kosten per ton CO2 reductie

**Comment by eoudejans** [comment]
S1 metakaartlagen nog (aan) te vullen:
- [ ] H01: totaal energieverbruik
- [ ] H02: energieverbruik ruimteverwarming
- [ ] H03: energieverbruik warm tapwater
- [ ] H04: energieverbruik ventilatie
- [ ] H05: energieverbruik koude
- [ ] H06: energieverbruik apparaten en licht
- [ ] H07: warmteverbruik
- [ ] H08: energielevering
- [ ] H09: energielevering aardgas
- [ ] H10: energielevering duurzaam gas
- [ ] H11: energielevering elektriciteit
- [ ] H12: energielevering MT-warmtebron
- [ ] H13: energielevering LT-warmtebron
- [ ] H14: energielevering overig
- [ ] H15: CO2-uitstoot
- [ ] H16: nationale meerkosten
- [ ] H17: nationale kosten per ton CO2 reductie
- [ ] H18: nationale kosten per ton CO2 reductie

**Comment by eoudejans** [comment]
S2 metakaartlagen nog (aan) te vullen:
- [ ] H01: totaal energieverbruik
- [ ] H02: energieverbruik ruimteverwarming
- [ ] H03: energieverbruik warm tapwater
- [ ] H04: energieverbruik ventilatie
- [ ] H05: energieverbruik koude
- [ ] H06: energieverbruik apparaten en licht
- [ ] H07: warmteverbruik
- [ ] H08: energielevering
- [ ] H09: energielevering aardgas
- [ ] H10: energielevering duurzaam gas
- [ ] H11: energielevering elektriciteit
- [ ] H12: energielevering MT-warmtebron
- [ ] H13: energielevering LT-warmtebron
- [ ] H14: energielevering overig
- [ ] H15: CO2-uitstoot
- [ ] H16: nationale meerkosten
- [ ] H17: nationale kosten per ton CO2 reductie
- [ ] H18: nationale kosten per ton CO2 reductie

**Comment by eoudejans** [comment]
S3 metakaartlagen nog (aan) te vullen:
- [ ] H01: totaal energieverbruik
- [ ] H02: energieverbruik ruimteverwarming
- [ ] H03: energieverbruik warm tapwater
- [ ] H04: energieverbruik ventilatie
- [ ] H05: energieverbruik koude
- [ ] H06: energieverbruik apparaten en licht
- [ ] H07: warmteverbruik
- [ ] H08: energielevering
- [ ] H09: energielevering aardgas
- [ ] H10: energielevering duurzaam gas
- [ ] H11: energielevering elektriciteit
- [ ] H12: energielevering MT-warmtebron
- [ ] H13: energielevering LT-warmtebron
- [ ] H14: energielevering overig
- [ ] H15: CO2-uitstoot
- [ ] H16: nationale meerkosten
- [ ] H17: nationale kosten per ton CO2 reductie
- [ ] H18: nationale kosten per ton CO2 reductie

**Comment by eoudejans** [comment]
S4 metakaartlagen nog (aan) te vullen:
- [ ] H01: totaal energieverbruik
- [ ] H02: energieverbruik ruimteverwarming
- [ ] H03: energieverbruik warm tapwater
- [ ] H04: energieverbruik ventilatie
- [ ] H05: energieverbruik koude
- [ ] H06: energieverbruik apparaten en licht
- [ ] H07: warmteverbruik
- [ ] H08: energielevering
- [ ] H09: energielevering aardgas
- [ ] H10: energielevering duurzaam gas
- [ ] H11: energielevering elektriciteit
- [ ] H12: energielevering MT-warmtebron
- [ ] H13: energielevering LT-warmtebron
- [ ] H14: energielevering overig
- [ ] H15: CO2-uitstoot
- [ ] H16: nationale meerkosten
- [ ] H17: nationale kosten per ton CO2 reductie
- [ ] H18: nationale kosten per ton CO2 reductie

**Comment by eoudejans** [comment]
S5 metakaartlagen nog (aan) te vullen:
- [ ] H01: totaal energieverbruik
- [ ] H02: energieverbruik ruimteverwarming
- [ ] H03: energieverbruik warm tapwater
- [ ] H04: energieverbruik ventilatie
- [ ] H05: energieverbruik koude
- [ ] H06: energieverbruik apparaten en licht
- [ ] H07: warmteverbruik
- [ ] H08: energielevering
- [ ] H09: energielevering aardgas
- [ ] H10: energielevering duurzaam gas
- [ ] H11: energielevering elektriciteit
- [ ] H12: energielevering MT-warmtebron
- [ ] H13: energielevering LT-warmtebron
- [ ] H14: energielevering overig
- [ ] H15: CO2-uitstoot
- [ ] H16: nationale meerkosten
- [ ] H17: nationale kosten per ton CO2 reductie
- [ ] H18: nationale kosten per ton CO2 reductie

**Comment by eoudejans** [comment]
R19 metakaartlagen nog (aan) te vullen:
- [x] H01: totaal energieverbruik
- [x] H02: energieverbruik ruimteverwarming
- [x] H03: energieverbruik warm tapwater
- [x] H04: energieverbruik ventilatie
- [x] H05: energieverbruik koude
- [x] H06: energieverbruik apparaten en licht
- [x] H07: warmteverbruik
- [x] H08: energielevering
- [x] H09: energielevering aardgas
- [x] H10: energielevering duurzaam gas
- [x] H11: energielevering elektriciteit
- [x] H12: energielevering MT-warmtebron
- [x] H13: energielevering LT-warmtebron
- [x] H14: energielevering overig
- [x] H15: CO2-uitstoot
- [x] H16: nationale meerkosten
- [x] H17: nationale kosten per ton CO2 reductie
- [x] H18: nationale kosten per ton CO2 reductie

**Comment by eoudejans** [comment]
R30 metakaartlagen nog (aan) te vullen:
- [x] H01: totaal energieverbruik
- [x] H02: energieverbruik ruimteverwarming
- [x] H03: energieverbruik warm tapwater
- [x] H04: energieverbruik ventilatie
- [x] H05: energieverbruik koude
- [x] H06: energieverbruik apparaten en licht
- [x] H07: warmteverbruik
- [x] H08: energielevering
- [x] H09: energielevering aardgas
- [x] H10: energielevering duurzaam gas
- [x] H11: energielevering elektriciteit
- [x] H12: energielevering MT-warmtebron
- [x] H13: energielevering LT-warmtebron
- [x] H14: energielevering overig
- [x] H15: CO2-uitstoot
- [x] H16: nationale meerkosten
- [x] H17: nationale kosten per ton CO2 reductie
- [x] H18: nationale kosten per ton CO2 reductie
